version: "3.9"

services:
  bot:
    build: .
    container_name: telegram_bot
    command: python bot.py
    restart: always
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}

  loader:
    build: .
    container_name: data_loader
    command: python sample_vendors.py
    restart: "no" 
    volumes:
      - .:/app
    environment:
      - DB_URL=${DB_URL}