services:
  bot:
    build: .
    container_name: telegram_bot
    command: python bot.py
    restart: always
    volumes:
      - ./data:/app/data  
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      loader:
        condition: service_completed_successfully
        
  loader:
    build: .
    container_name: data_loader
    command: python sample_vendors.py
    restart: "no"
    volumes:
      - ./data:/app/data  
    environment:
      - DB_URL=${DB_URL}